spring:
    application.name: beer-api-producer
    cloud.stream.bindings.output:
        content-type: application/json
server.port: ${PORT:8080}
logging:
  level:
    org.springframework.cloud: debug
